# Generated by Django 4.2.7 on 2023-12-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='resident_id',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
    ]
