# Generated by Django 4.2.7 on 2023-12-09 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bisapp', '0003_incidentreport_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='report_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
