# Generated by Django 4.2.7 on 2023-12-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisapp', '0005_rename_resident_id_incidentreport_reported_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='reported_id',
            new_name='reporter_id',
        ),
    ]
