# Generated by Django 4.2.7 on 2023-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisapp', '0006_rename_reported_id_incidentreport_reporter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reporter_id',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
